Import('env')

env.Append(CPPPATH=['.'])
env['CPPPATH'].append('./geoformat')

penv = env.Clone()
penv.Append(LIBS=['gdal'],LIBPATH=[env['ENV']['GDAL_LIB']],CPPPATH=[env['ENV']['GDAL_INCLUDE']])
penv.Library('geoformat',Glob('*.cpp'))
