Import('env')
Import('modules')

penv = env.Clone()

for subdir in modules:
    penv.SConscript("%s/SConscript" % subdir,{'env':env})

penv['CPPPATH'].append('./geoformat')
penv['CPPPATH'].append('./mpiobject')

penv['LIBPATH'].append(penv['ENV']['GDALLIB'])
penv['LIBPATH'].append(penv["ENV"]["MPILIB"])

penv['CPPPATH'].append(penv['ENV']['GDALINC'])
penv['CPPPATH'].append(penv["ENV"]["MPIINC"])
penv.Program('hpgc',Glob('*.cpp'),LIBS=['geoformat','mpiobject','gdal_i','mpi'])
