Import('env')
Import('modules')

penv = env.Clone()

for subdir in modules:
    penv.SConscript("%s/SConscript" % subdir,{'env':env})

penv['CPPPATH'].append('./geoformat')
penv['LIBPATH'].append('./geoformat')

penv['LIBPATH'].append(penv["ENV"]["GDAL_LIB"])
penv['CPPPATH'].append(penv["ENV"]["GDAL_INCLUDE"])

penv['LIBPATH'].append(penv["ENV"]["MPI_LIB"])
penv['CPPPATH'].append(penv["ENV"]["MPI_INCLUDE"])

penv['LIBPATH'].append(penv["ENV"]["PROTO_LIB"])
penv['CPPPATH'].append(penv["ENV"]["PROTO_INCLUDE"])

penv['LIBPATH'].append(penv["ENV"]["GLOG_LIB"])
penv['CPPPATH'].append(penv["ENV"]["GLOG_INCLUDE"])

penv.Program('hpgc',Glob('*.cpp'),LIBS=['geoformat','glog','protobuf','gdal','mpi','mpi_cxx'])
